# Conclusion

On this project we deepened on the health status of people living in the United States, and how it relates with other social, cultural, and economic dimensions.

First, we showed through a [weighted bar chart](https://dtung8068.github.io/cps-asec-2023/results.html#a-first-overview) that more than 60% of the U.S. population enjoy a really good ("very good" or "excellent") state of health. However, there is also about 11% of the U.S. population that suffer a weak ("fair" or "poor") health status.

Second, through a [faceted histogram](https://dtung8068.github.io/cps-asec-2023/results.html#an-expected-relationship-health-and-age) we confirmed a well-known fact: there is a negative correlation between health and age. In other words, young people are healthier than older people.

Third, we studied how the health status relates with sex, age and employment using [mosaic plots](https://dtung8068.github.io/cps-asec-2023/results.html#association-between-health-and-dimensions-race-sex-and-employment). We found that the proportion of women that suffers a weak state of health is greater than the proportion of men. Similarly, the proportion of black people with weak health is greater than the proportion corresponding to white or asian people. In addition, we noted that for all races and sex, the employed people have a better health than the unemployed ones. Furthermore, the group of people that has the highest proportion of people with weak health is the unemployed black women, showing inequalities on health across U.S. people in terms of sex, race and employment status.

In addition, we analyzed how the earnings of employed people relates to health via a [faceted ridgeline plots with boxplots](https://dtung8068.github.io/cps-asec-2023/results.html#how-does-earnings-associate-with-health). From this analysis, it followed that the distribution of earnings is right-skewed for every category of health status. And, more importantly, there is a positive correlation between earnings and health. For instance, the median of earnings increases with health status. Then, it appears to be true that wealthier people enjoys a better state of health than poorer people. To deepen on this, we build a [d3 interactive graph](https://dtung8068.github.io/cps-asec-2023/d3graph.html) with five boxplots showing the distribution of earnings of employed people for each health status.

Furthermore, we studied whether or not more educated people are healthier. To analyze that we plotted two [faceted heat maps](https://dtung8068.github.io/cps-asec-2023/results.html#are-more-educated-people-healthier), the first one faceted by citizenship and the second one by race. We found that it is quite probable for a person who enjoys a really good health status to have an advanced education degree (bachelor or higher) and it is quite unlikely to not have completed at least high school. In other words, we found that there exists a positive correlation between health and educational attainment. Although there are some differences, it is true for every citizenship category (Native, Naturalized and Not US Citizen) and for every race (White, Black and Asian).

In addition, we studied through a [interactive faceted scatterplot](https://dtung8068.github.io/cps-asec-2023/results.html#expenditure-on-health) how the expenditure on health changes across the different health status and with income. First, we showed that there is a positive correlation between the income and the expenditure on health. In addition, people who enjoy a better state of health tend to be richer and also to spend more money on health. When it comes to insurance coverage, we concluded that most people in the U.S. have insurance coverage, regardless of their health status.

Furthermore, we analyzed with an [interactive parallel coordinates plot] the relation between income, earnings and medical expenses for each category of health status. We outlined that the sample drew on the graph suggest a positive correlation between income and earnings, and earnings and the money spent on medical expenditures.

Finally, we analyzed through two [interactive stacked bar charts](https://dtung8068.github.io/cps-asec-2023/results.html#distribution-of-health-status-across-states) how the distribution of health status changes across states. There is heterogeneity across states, being Utah, South Dakota, Connecticut, Idaho, New Hampshire and Colorado the states having the best performance, in terms of the smallest proportion of people that suffer a weak state of health. On the contrary, Mississippi, Kentucky, West Virginia, Arkansas and New Mexico are the states with the highest share of population suffering a weak state of health (Mississippi about 18% of the population). When we faceted by race, we found that for almost every state, the portion of the population that suffers a weak state of health (i.e., fair or poor) is greater for the black race than for the white race. Finally, the asian community appears to have an overall good state of health, even better than white people in many states.

