# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
</style>
<div id="plot">
<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

Use the slider to adjust the x-axis. The x-axis ranges from 0 to 2 in intervals of 0.1, representing annual earnings in millions of dollars. If you want to remove outliers, click on "Remove Outliers", which will remove any outliers up to 0.2 million.

We already know from Section 3.5 that all the earnings are right-skewed and Q1, median, and Q3 are all positively correlated with health status. Adjusting the slider allows us to see how exactly these values differ. More specifically, we can see that median income varies between 0.03 million and 0.05 million ($30k - 50k) while upper quantile income varies between 0.055 million and 0.09 million ($55k - 90k). Lower quantile is quite interesting because we can see that people with Excellent and Very Good health have identical lower quantiles (roughly $30k income). On top of indicating that the positive correlation is not as strong as previously suggested, it also indicates that 75% more people with Excellent or Very Good health make at least $30k annually compared to just 50% of people with Poor health.
